// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fmowxizbfmfrcyyomzew.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZtb3d4aXpiZm1mcmN5eW9temV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MzA3OTIsImV4cCI6MjA3MTEwNjc5Mn0.pUNLvk12_CuekWU7iQkvCFnvDM8jv-QSIGB3bKtCAOQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});